Script improvements

diff --git a/extrack b/extrack
--- a/extrack
+++ b/extrack
@@ -4,37 +4,62 @@
 #  A script for extracting a specific track id from
 #  media files that are supported by ffmpeg.
 #
-#  Passing a directory will extract the track id from
-#  all ffmpeg compatible media files inside the folder.
-#
-#  - Requries ffmpeg to be installed to work.
+#  Requirements:
+#    FFmpeg
 #
 #  Usage:
-#  extrack <File / Directory> <Track ID> <File Format>
+#    extrack <File / Directory> <Track ID> <File Format>
+#
+#  Notes:
+#    Passing a directory will extract the track id from
+#    all ffmpeg compatible media files inside the folder.
 #  ---------------------------------------------------
 
-usage="$(basename \"$0\") <File / Directory> <Track ID> <File Format>
-\nExamples: $(basename "$0") \"/media/movies/file.mkv\" 1 srt
-\n          $(basename "$0") \"/media/movies\" 1 srt"
 
-ffmpeg_extract()
+#######################################
+# Extract a track from an mkv file.
+#
+# Arguments:
+#   #1 - Path to an mkv file
+#   #2 - Track ID to extract
+#   #3 - File format to save track as
+#
+# Outputs:
+#   Extract the track to a separate file.
+#######################################
+function ffmpeg_extract
 {
-    ffmpeg -hide_banner -v error -stats -i "$1" -c copy -map 0:$2 "$(basename "$1" | sed "s/^\(.*\)\..*$/\1/").$3" -y
+    result_file_name="$(basename "$1" | sed "s/^\(.*\)\..*$/\1/").${3}"
+    ffmpeg -hide_banner -v "error" -stats -i "$1" -c copy -map 0:${2} "$result_file_name" -y
 }
 
-# Assure a valid amount of command-line arguments was passed
-if [[ $# == 3 ]]; then
-    # Directory
-    if [[ -d "$1" ]]; then
-        cd -- "$1"
-        for file in "$1"/* ; do
-            ffmpeg_extract "$file" $2 $3
-            done
+function pring_usage
+{
+    echo "Usage: $(basename "$0") <File / Directory> <Track ID> <File Format>"
+}
 
-    # Single file
-    elif [[ -f "$1" ]]; then
-        ffmpeg_extract "$1" $2 $3
-    fi
-else
-    echo -e "$usage"
+
+# Assure a valid amount of command-line arguments was passed
+if [[ $# -lt 3 ]]; then
+    echo "Error: Missing parameters." >&2
+    pring_usage
+    exit 1
+fi
+
+# Assure file / directory exists
+if [[ ! -e "$1" ]]; then
+    echo "Error: Directory / file \"$1\" not found." >&2
+    pring_usage
+    exit 1
+fi
+
+# Path parameter ($1) is a directory
+if [[ -d "$1" ]]; then
+    for file in "$1"/*.mkv ; do
+        ffmpeg_extract "$file" "$2" "$3"
+    done
+
+# Path parameter ($1) is a file
+elif [[ -f "$1" ]]; then
+    ffmpeg_extract "$1" "$2" "$3"
 fi
diff --git a/genlinks b/genlinks
--- a/genlinks
+++ b/genlinks
@@ -1,57 +1,76 @@
 #!/bin/bash
 
 #  --------------------- genlinks ---------------------
-#  A script for generating symlinks. 
-#  The script will duplicate source's directory structure
-#  to destination with symlinks instead of files.
-#
-#  Passing file extensions allow filtering and will create 
-#  symlinks only for files with the file extensions that were passed.
+#  A script for generating symlinks.
+#  If a directory is passed, the script will duplicate it's structure
+#  to the destination with symlinks instead of files.
 #
 #  Usage:
-#  genlinks <Source File / Directory> <Destination Directory> [<File Extensions>...]
+#    genlinks <Source File / Directory> <Destination Directory> [<File Extensions>...]
+#
+#  Notes:
+#    Passing file extensions will filter the files and create symlinks
+#    only for files with file extensions that match the ones that were passed.
 #  ----------------------------------------------------
 
-usage="$(basename "$0") <Source File / Directory> <Destination Directory> [<File Extensions>...]\n
-Examples: $(basename "$0") \"/downloads/movie.mkv\" \"/media/\"
-          $(basename "$0") \"/downloads/\" \"/media/\" mkv mp4"
+
+function pring_usage
+{
+    echo "Usage: $(basename "$0") <Source File / Directory> <Destination Directory> [<File Extensions>...]"
+}
+
 
 # Assure a valid amount of command-line arguments was passed
-if (($# >= 2)); then
-	# Assure source file / directory exists
-	if [[ ! -e "$1" ]]; then
-		echo -e "Source file / folder "$1" doesn't exist."
+if [[ $# -lt 2 ]]; then
+    echo "Error: Missing parameters." >&2
+    pring_usage
+    exit 1
+fi
 
-	else
-		# Convert paths to absolute (in case they're relative)
-		source_dir="$(realpath "$1")"
-		destination_dir="$(realpath "$2")"
+# Assure source file / directory exists
+if [[ ! -e "$1" ]]; then
+	echo -e "Source file / folder "$1" doesn't exist."
+fi
 
-		# Single file
-		if [[ -f "$source_dir" ]]; then
-			ln --symbolic -- "$source_dir" "$2"
+# Remove trailing '/' if it exists
+source_dir=${1%/}
+destination_dir=${2%/}
 
-		# Directory
-		elif  [[ -d "$source_dir" ]]; then
-			# Default value - matches all filenames
-			regex=".*"
+# Source parameter ($1) is a file
+if [[ -f "$source_dir" ]]; then
+	ln --symbolic -- "$source_dir" "$2"
 
-			# If file extensions were passed
-			if [[ $# > 2 ]]; then
-				# Generate and replace default iregex expression
-				regex="$(echo ".*\(${@:3}\)" | sed 's/ /\\|/g')"
-			fi
-			
-			cd -- "$source_dir"
-			# Reconstruct source directory structure in destination directory
-			find * -type d -exec mkdir --parents -- "$destination_dir"/"{}" \;
-			# Generate symlinks
-			find * -type f -iregex "$regex" -exec ln --symbolic -- "$source_dir"/"{}" "$destination_dir"/"{}" \;
-			# Remove empty folders
-			find -type d -empty -delete
-		fi
+# Source parameter ($1) is a directory
+elif  [[ -d "$source_dir" ]]; then
+	# Default value - matches all filenames
+	regex=".*"
+
+	# If file extensions were passed
+	if [[ $# > 2 ]]; then
+		# Generate and replace default iregex expression
+		regex="$(echo ".*\("${@:3}"\)$" | sed 's/ /\\|/g')"
 	fi
+	
+	cd -- "$source_dir"
 
-else
-    echo -e "$usage"
+	# Generate symlinks for files in root directory
+	find * -type f -maxdepth 0 -iregex "$regex" \
+	-exec ln --symbolic -- "$source_dir"/{} "$destination_dir"/{} \;
+
+	# List of files matching the file extensions filter that are in subdirectories
+	subdir_files="$(find * -mindepth 1 -type f -iregex "$regex")"
+
+	# Generate subdirectories
+	while read path; do
+		new_subdir_path="$destination_dir"/$(dirname "$path")
+
+		if [[ ! -d "$new_subdir_path" ]]; then
+			mkdir --parents "$new_subdir_path"
+		fi
+	done <<< "$subdir_files"
+
+	# Generate symlinks
+	while read path; do
+		ln --symbolic -- "$source_dir"/"$path" "$destination_dir"/"$path"
+	done <<< "$subdir_files"
 fi
